//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboTemplateDetail
    {
        public int TemplateDetailID { get; set; }
        public int TemplateID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> VariantID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ComboTemplate ComboTemplate { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
