//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> VariantID { get; set; }
        public string TransactionType { get; set; }
        public int Quantity { get; set; }
        public int PreviousStock { get; set; }
        public int NewStock { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ReferenceID { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
