//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductReviews = new HashSet<ProductReview>();
        }
    
        public int OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Status { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string PaymentStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> ShippingID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Promotion Promotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
