//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComboDetail
    {
        public int ComboDetailID { get; set; }
        public int ComboID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> VariantID { get; set; }
        public int Quantity { get; set; }
    
        public virtual ProductCombo ProductCombo { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
