//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int CartID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> VariantID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
